Added set -e and set -o pipefail and xzcat

diff --git a/bin/apt-cyg b/bin/apt-cyg
--- a/bin/apt-cyg
+++ b/bin/apt-cyg
@@ -25,16 +25,25 @@
 # - 2013-09-26: Find: two new options: --ignore-case, --available-only
 # - 2013.11.06: Added yum like args (search info provides ...)
 #               added --no-verbose to wget calls
+# - 2013.12.03: added xz decompression
+#               adding set -e and set -o pipefail for uncompress failures
+set -e 
+set -o pipefail
 
 WGET=`which wget 2> /dev/null`
 BZIP2=`which bzip2 2> /dev/null`
+BZCAT=`which bzcat 2> /dev/null`
 XZ=`which xz 2> /dev/null`
+XZCAT=`which xzcat 2> /dev/null`
 TAR=`which tar 2> /dev/null`
 GAWK=`which awk 2> /dev/null`
-if test "-$WGET-" = "--" || test "-$BZIP2-" = "--" || test "-$TAR-" = "--" \
-  || test "-$GAWK-" = "--"
+if test "-$WGET-" = "--" \
+  || test "-$TAR-" = "--" \
+  || test "-$GAWK-" = "--" \
+  || test "-$BZIP2-" = "--" || test "-$BZCAT-" = "--" \
+  || test "-$XZ-" = "--" || test "-$XZCAT-" = "--"
 then
-  echo You must install wget, tar, gawk and bzip2 to use apt-cyg.
+  echo You must install wget, tar, gawk, xz and bzip2 to use apt-cyg.
   exit 1
 fi
 
@@ -378,7 +387,7 @@ case "$command" in
     fi
     echo Found package $pkg
 
-    # download and unpack the bz2 file
+    # download and unpack the file
 
     # pick the latest version, which comes first
     install=`cat "release/$pkg/desc" | awk '/^install: / { print $2; exit }'`
@@ -391,6 +400,7 @@ case "$command" in
 
     file=`basename $install`
     cd "release/$pkg"
+
     wget --no-verbose -nc $mirror/$install
 
     # check the md5
@@ -403,7 +413,13 @@ case "$command" in
     fi
 
     echo "Unpacking..."
-    cat $file | bunzip2 | tar > "/etc/setup/$pkg.lst" xvf - -C /
+    # this does not test for extension... nor does it see if the uncompress failed
+    #cat $file | bunzip2 | tar > "/etc/setup/$pkg.lst" xvf - -C /
+
+    # hack to decompress by either bzcat or xzcat depending in the extension
+    ext=${file##*.}	# should be .bz2 or .xz but not testing this
+    ${ext:0:1}zcat $file | tar > "/etc/setup/$pkg.lst" xvf - -C /
+
     gzip -f "/etc/setup/$pkg.lst"
     cd ../..
 
